### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by MattBlack85** [kevin1024/vcrpy#134]
Hi, I'm having this error today with vcrpy, here's the traceback:
```
Traceback (most recent call last):
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/vcr/cassette.py", line 65, in __call__
    return function(*args, **kwargs)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/vcr/cassette.py", line 59, in __exit__
    next(self.__finish, None)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/vcr/cassette.py", line 50, in _patch_generator
    cassette._save()
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/vcr/cassette.py", line 195, in _save
    serializer=self._serializer
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/vcr/persist.py", line 13, in save_cassette
    data = serialize(cassette_dict, serializer)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/vcr/serialize.py", line 63, in serialize
    return serializer.serialize(data)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/vcr/serializers/yamlserializer.py", line 15, in serialize
    return yaml.dump(cassette_dict, Dumper=Dumper)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 215, in represent_list
    return self.represent_sequence(u'tag:yaml.org,2002:seq', data)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 101, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 61, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 434, in represent_object
    u'tag:yaml.org,2002:python/object:'+function_name, state)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 61, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/matt/repos/uwncom/lib/python2.7/site-packages/yaml/representer.py", line 408, in represent_object
    reduce = data.__reduce_ex__(2)
ValueError: I/O operation on closed file.

```
I'm making a POST request with a file and it seems that cannot be accomplished for some reasons, do you know what I'm doing wrong?

**Comment by IvanMalison** [comment]
Can you post the exactly line that you suspect is causing this error?

**Comment by kevin1024** [comment]
I wonder if this is related to #121.  I think yaml is having trouble serializing a closed file.

**Comment by MattBlack85** [comment]
@IvanMalison the line which "causes" the error is:
```
return Response(data=asset_id, status=status.HTTP_201_CREATED)
```
basically no error is raised unti vcr start to make its own job

**Comment by IvanMalison** [comment]
@MattBlack85 Can you check to see if #141 solved your issue? The new code hasn't made it in to a release yet, so you'll have to use the version that is currently on master manually. Let me know if you need help setting that up.

**Comment by MattBlack85** [comment]
sure, I'll try it asap!

**Comment by IvanMalison** [comment]
@MattBlack85 update?

Can you show me the test case that caused this issue. I'd like to make a new vcrpy release, but I want to make sure this issue is fixed before I do.

**Comment by MattBlack85** [comment]
@IvanMalison I just tried installing from master and I'm not getting anymore the I/O error!

**Comment by IvanMalison** [comment]
Okay. Can i consider the issue solved?

**Comment by MattBlack85** [comment]
Yep, we close this
