### ISSUE TITLE
"TypeError: Can't convert 'bytes' object to str implicitly" whilst recording 'requests' session.

### ISSUE THREAD

**Issue by MrJohz** [kevin1024/vcrpy#158]
Specifically, whilst removing post parameters:

```python
    def remove_post_data_parameters(request, post_data_parameters_to_remove):
        if request.method == 'POST' and not isinstance(request.body, BytesIO):
            if ('Content-Type' in request.headers and
                    request.headers['Content-Type'] == 'application/json'):
                json_data = json.loads(request.body.decode('utf-8'))
                for k in list(json_data.keys()):
                    if k in post_data_parameters_to_remove:
                        del json_data[k]
                request.body = json.dumps(json_data).encode('utf-8')
            else:
                post_data = OrderedDict()
                # fails on following line due to bytes/str incompatibility.
                for k, sep, v in [p.partition(b'=') for p in request.body.split(b'&')]:
                    if k in post_data:
```

Example file that will fail:
```python
import vcr
import requests

player = vcr.VCR(
    serializer='yaml',
    record_mode='once',
    cassette_library_dir='cassettes',
    match_on=['uri', 'method'],
    filter_post_data_parameters=['username', 'password'])

post_body = {'username': 'top-secret-needs-filtering',
             'password': 'top-secret-needs-filtering'}

with player.use_cassette('test_post.yaml'):
    requests.post('http://httpbin.org/post', data=post_body)
```

Example console shell of previous file:
```console
$ python --version
Python 3.4.2

$ pip freeze
backport-collections==0.1
contextlib2==0.4.0
mock==1.0.1
PyYAML==3.11
requests==2.7.0
six==1.9.0
vcrpy==1.5.2
wrapt==1.10.4

$ python fail.py 
Traceback (most recent call last):
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/vcr/stubs/__init__.py", line 219, in getresponse
    if self.cassette.can_play_response_for(self._vcr_request):
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/vcr/cassette.py", line 201, in can_play_response_for
    request = self._before_record_request(request)
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/vcr/config.py", line 216, in before_record_request
    request = function(request)
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/vcr/filters.py", line 44, in remove_post_data_parameters
    for k, sep, v in [p.partition(b'=') for p in request.body.split(b'&')]:
TypeError: Can't convert 'bytes' object to str implicitly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fail.py", line 15, in <module>
    requests.post('http://httpbin.org/post', data=post_body)
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/vcr/stubs/__init__.py", line 219, in getresponse
    if self.cassette.can_play_response_for(self._vcr_request):
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/vcr/cassette.py", line 201, in can_play_response_for
    request = self._before_record_request(request)
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/vcr/config.py", line 216, in before_record_request
    request = function(request)
  File "/home/jonathan/.pyenv/versions/failvcrpy/lib/python3.4/site-packages/vcr/filters.py", line 44, in remove_post_data_parameters
    for k, sep, v in [p.partition(b'=') for p in request.body.split(b'&')]:
TypeError: Can't convert 'bytes' object to str implicitly

**Comment by IvanMalison** [comment]
Closed by #159
