### ISSUE TITLE
AttributeError: 'module' object has no attribute 'evaluate_marker'

### ISSUE THREAD

**Issue by charlax** [kevin1024/vcrpy#178]
I'm getting the following when trying to install `vcrpy`:

```
Downloading/unpacking vcrpy==1.6.1 (from -r requirements-tests.txt (line 12))
  Using download cache from ...
  Running setup.py egg_info for package vcrpy
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File ".../env/build/vcrpy/setup.py", line 36, in <module>
        if key.startswith(':') and pkg_resources.evaluate_marker(key[1:]):
    AttributeError: 'module' object has no attribute 'evaluate_marker'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File ".../env/build/vcrpy/setup.py", line 36, in <module>

    if key.startswith(':') and pkg_resources.evaluate_marker(key[1:]):

AttributeError: 'module' object has no attribute 'evaluate_marker'
```

**Comment by charlax** [comment]
This happens when using `distribute-0.6.34-py2.7.egg`, which is pretty old.

**Comment by IvanMalison** [comment]
@graingert Wrote this. Is there any reason you can't upgrade?

**Comment by graingert** [comment]
> Distribute is no longer being maintained.

https://pythonhosted.org/distribute/

**Comment by Lushali** [comment]
I upgraded distribute, but the error stays.

Upgrade:
```
pip install --upgrade distribute --user
Collecting distribute
  Downloading distribute-0.7.3.zip (145kB)
    100% |████████████████████████████████| 153kB 2.7MB/s 
Collecting setuptools>=0.7 (from distribute)
  Using cached setuptools-36.0.1-py2.py3-none-any.whl
Building wheels for collected packages: distribute
  Running setup.py bdist_wheel for distribute ... done
  Stored in directory: /Users/lilusha/Library/Caches/pip/wheels/ef/17/3f/3f837ef0521dcfb5da75a00488fef1ac1747d74edbddeb27e6
Successfully built distribute
Installing collected packages: setuptools, distribute
Successfully installed distribute-0.7.3 setuptools-36.0.1
```

Error:
```
Installed /private/tmp/easy_install-l8MoYR/mock-2.0.0/pbr-3.1.1-py2.7.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/private/tmp/easy_install-l8MoYR/mock-2.0.0/pbr-3.1.1-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/private/tmp/easy_install-l8MoYR/mock-2.0.0/pbr-3.1.1-py2.7.egg/pbr/util.py", line 251, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/private/tmp/easy_install-l8MoYR/mock-2.0.0/pbr-3.1.1-py2.7.egg/pbr/util.py", line 434, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
AttributeError: 'module' object has no attribute 'evaluate_marker'
error: Setup script exited with error in setup command: Error parsing /private/tmp/easy_install-l8MoYR/mock-2.0.0/setup.cfg: AttributeError: 'module' object has no attribute 'evaluate_marker'
```

**Comment by graingert** [comment]
@Lushali distribute is dead, why would you install it?

Always install the pypa trifecta:

`pip install -U pip setuptools wheel`

**Comment by graingert** [comment]
@Lushali also that's a bug in pbr that mock is using
