### ISSUE TITLE
UnicodeEncodeError under Python 3 if request body contains URL-encoded non-ASCII chars

### ISSUE THREAD

**Issue by gward** [kevin1024/vcrpy#185]
If all of the following are true:
- Python 3
- `match_on` contains `body`
- request body is URL-encoded non-ASCII string
- attempting to replay a previously recorded cassette

then VCR.py blows up with "UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 0: ordinal not in range(128)" (full stack trace below).

Here's a demo script:

```
$ cat unicode-body.py
from __future__ import print_function
from six.moves import urllib
import vcr

myvcr = vcr.VCR(match_on=('method', 'scheme', 'host', 'port', 'path', 'query', 'body'))

params = {b'foo': u'\u00e9'.encode('utf-8')}
print('params:', params)
data = urllib.parse.urlencode(params).encode('ascii')
print('data:', data)

with myvcr.use_cassette('unicode-body.yaml'):
    req = urllib.request.Request(url='http://httpbin.org/post', data=data)
    resp = urllib.request.urlopen(req)

print(resp.read().decode('utf-8'), end='')
```

This works fine under Python 2, both without and with a recorded cassette:

```
$ rm -f unicode-body.yaml && python unicode-body.py                        
params: {'foo': '\xc3\xa9'}
data: foo=%C3%A9
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
    "foo": "\u00e9"
  }, 
  "headers": {
    "Accept-Encoding": "identity", 
    "Content-Length": "10", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "Python-urllib/2.7"
  }, 
  "json": null, 
  "origin": "69.165.200.93", 
  "url": "http://httpbin.org/post"
}
$ python unicode-body.py                        
params: {'foo': '\xc3\xa9'}
data: foo=%C3%A9
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
    "foo": "\u00e9"
  }, 
  "headers": {
    "Accept-Encoding": "identity", 
    "Content-Length": "10", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "Python-urllib/2.7"
  }, 
  "json": null, 
  "origin": "69.165.200.93", 
  "url": "http://httpbin.org/post"
}
```

Under Python 3, it works fine the _first_ time, when I actually run the HTTP request:

```
$ rm -f unicode-body.yaml && python unicode-body.py
params: {b'foo': b'\xc3\xa9'}
data: b'foo=%C3%A9'
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
    "foo": "\u00e9"
  }, 
  "headers": {
    "Accept-Encoding": "identity", 
    "Content-Length": "10", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "Python-urllib/3.4"
  }, 
  "json": null, 
  "origin": "69.165.200.93", 
  "url": "http://httpbin.org/post"
}
```

But the second time, trying to replay the recorded cassette, blows up:

```
$ python unicode-body.py      
params: {b'foo': b'\xc3\xa9'}
data: b'foo=%C3%A9'
Traceback (most recent call last):
  File "unicode-body.py", line 14, in <module>
    resp = urllib.request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1185, in do_open
    r = h.getresponse()
  File "/data/src/vcrpy/vcr/stubs/__init__.py", line 220, in getresponse
    if self.cassette.can_play_response_for(self._vcr_request):
  File "/data/src/vcrpy/vcr/cassette.py", line 218, in can_play_response_for
    return request and request in self and \
  File "/data/src/vcrpy/vcr/cassette.py", line 289, in __contains__
    for index, response in self._responses(request):
  File "/data/src/vcrpy/vcr/cassette.py", line 213, in _responses
    if requests_match(request, stored_request, self._match_on):
  File "/data/src/vcrpy/vcr/matchers.py", line 96, in requests_match
    matches = [(m(r1, r2), m) for m in matchers]
  File "/data/src/vcrpy/vcr/matchers.py", line 96, in <listcomp>
    matches = [(m(r1, r2), m) for m in matchers]
  File "/data/src/vcrpy/vcr/matchers.py", line 79, in body
    return transformer(read_body(r1)) == transformer(read_body(r2))
  File "/usr/lib/python3.4/urllib/parse.py", line 558, in parse_qs
    encoding=encoding, errors=errors)
  File "/usr/lib/python3.4/urllib/parse.py", line 610, in parse_qsl
    value = _coerce_result(value)
  File "/usr/lib/python3.4/urllib/parse.py", line 92, in _encode_result
    return obj.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 0: ordinal not in range(128)
```

**Comment by gward** [comment]
Just to make sure I didn't break things when I fixed #163, I tried my script under VCR.py v1.6.1. Same result.

**Comment by IvanMalison** [comment]
Hah wow. nice edge case. How do you keep hitting these?
This makes sense. It's because request matching would only happen the second time anyway. My guess is that we need to explicity decode the string from utf-8

**Comment by gward** [comment]
> Hah wow. nice edge case. How do you keep hitting these?

Just lucky, I guess! ;-)

But seriously: we have a collection of existing HTTP client libraries that work under Python 2, so I've been doing the initial conversion to VCR.py (either write tests from scratch or convert existing tests) under Python 2. Also we frequently use POST to send large queries, so we need to match on request bodies. And since we now need to support Python 3, I'm adding tests with non-ASCII strings to make sure we don't hit unexpected UnicodeErrors in production. Combine those factors and I'm well-placed to find edge cases in VCR.py.

**Comment by cjw296** [comment]
```
params = {b'foo': u'\u00e9'.encode('utf-8')}
print('params:', params)
data = urllib.parse.urlencode(params).encode('ascii')
```
@gward - are you sure about the above?

You'r encoding using utf-8, and then again using ascii. It's the latter one that's blowing up. You should have bytes by then, curious as to why you don't...

**Comment by maxking** [comment]
I along with my colleague were trying to debug this issue as it causes our own test suite to fail causing problems. It seems like this issue arises from `urllib.parse.parse_qsl` in the standard library specifically [here][1]. The method looks something like this:

```
def parse_qsl(qs, keep_blank_values=False, strict_parsing=False,
              encoding='utf-8', errors='replace'):
            qs, _coerce_result = _coerce_args(qs)
            .....
            value = _coerce_result(value)
            r.append((name, value))
    return r

# For 3.2, we deliberately require applications that
# handle improperly quoted URLs to do their own
# decoding and encoding. If valid use cases are
# presented, we may relax this by using latin-1
# decoding internally for 3.3
_implicit_encoding = 'ascii'
_implicit_errors = 'strict'
```
Note the `_implicit_encoding` or `ascii` above which is what `_coerce_result` method uses to try to force the result to instead of passing on the `encoding` variable which _correctly_ defaults to `utf-8`.


[1]: https://github.com/python/cpython/blob/master/Lib/urllib/parse.py#L703

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
