### ISSUE TITLE
Exception raised when using vcrpy==1.10.1 on Python 3

### ISSUE THREAD

**Issue by lamenezes** [kevin1024/vcrpy#274]
Easy (temp) fix: pin vcrpy version to 1.10.0

```
Traceback (most recent call last):
  File "/home/luiz/.virtualenvs/freights-api/lib/python3.5/site-packages/vcr/cassette.py", line 95, in __call__
    function, args, kwargs
  File "/home/luiz/.virtualenvs/freights-api/lib/python3.5/site-packages/vcr/cassette.py", line 103, in _execute_function
    return handler(function, args, kwargs)
  File "/home/luiz/.virtualenvs/freights-api/lib/python3.5/site-packages/vcr/cassette.py", line 129, in _handle_function
    with self as cassette:
  File "/home/luiz/.virtualenvs/freights-api/lib/python3.5/site-packages/vcr/cassette.py", line 82, in __enter__
    return next(self.__finish)
  File "/home/luiz/.virtualenvs/freights-api/lib/python3.5/site-packages/vcr/cassette.py", line 50, in _patch_generator
    for patcher in CassettePatcherBuilder(cassette).build():
  File "/home/luiz/.virtualenvs/freights-api/lib/python3.5/site-packages/vcr/patch.py", line 115, in _build_patchers_from_mock_triples
    for args in mock_triples:
  File "/home/luiz/.virtualenvs/freights-api/lib/python3.5/site-packages/vcr/patch.py", line 290, in _aiohttp
    from .stubs.aiohttp_stubs import vcr_request
ImportError: No module named 'vcr.stubs.aiohttp_stubs'
```

I'm going to check it as soon as I have the time.

**Comment by lamenezes** [comment]
@kevin1024 it seems the source on PyPI was generated using Python 2.7 and aiohttp_stubs weren't included.

**Comment by kevin1024** [comment]
OK, new release pushed with python3.
