### ISSUE TITLE
VCR doesn't work when Upgrade to 1.11.1

### ISSUE THREAD

**Issue by ooeyuna** [kevin1024/vcrpy#313]
it works fine at 1.10.5 and fail at 1.11.1

code:
```
import vcr

@vcr.use_cassette("natsuko/fixtures/vcr_cassettes/app_check.yaml")
def test_update_deploy_with_application_id(self):
    # dotest
```

it make real connection when yaml exist.

i tried to delete `app_check.yaml` and run test,but it cannot genarator new yaml file.

stack:
```
Traceback (most recent call last):
  File "/Users/sanairika/venv/lib/python3.5/site-packages/vcr/cassette.py", line 105, in __call__
    function, args, kwargs
  File "/Users/sanairika/venv/lib/python3.5/site-packages/vcr/cassette.py", line 120, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/Users/sanairika/venv/lib/python3.5/site-packages/vcr/cassette.py", line 141, in _handle_function
    return fn(cassette)
  File "/Users/sanairika/venv/lib/python3.5/site-packages/vcr/cassette.py", line 113, in handle_function
    return function(*args, **kwargs)
  File "/Users/sanairika/share/sakurako/natsuko/tests/test_views.py", line 339, in test_update_deploy_with_application_id
    self.assertEqual(202, res.status_code)
AssertionError: 202 != 403
```

all pip package
```
Django==1.10.2
django-filter==1.0.4
djangorestframework==3.5.3
docker-py==1.10.6
docker-pycreds==0.2.1
ecdsa==0.13
elasticsearch==1.6.0
future==0.16.0
heimdall==1.0a8
kafka-python==1.3.3
marathon==0.8.6
multidict==2.1.6
pycrypto==2.6.1
pystache==0.5.4
python-jose==0.6.1
PyYAML==3.12
requests==2.11.1
six==1.10.0
sseclient==0.0.18
urllib3==1.21.1
vcrpy==1.11.1
watcher==0.5b5
websocket-client==0.40.0
wrapt==1.10.10
yarl==0.10.2
```

**Comment by graingert** [comment]
Can you create a failing demo project? Eg make a new github repo and demonstrate the failure on Travis?

**Comment by ooeyuna** [comment]
[demo](https://github.com/ooeyuna/vcrtest)

`github.yml` will return status code 400

reproduction: 
- install requests==2.17.3
- install requests==2.11.1 vcrpy==1.11.1
- run test
