### ISSUE TITLE
Installation on Python 3.4.0 is failing

### ISSUE THREAD

**Issue by 5j9** [kevin1024/vcrpy#342]
https://ci.appveyor.com/project/5j9/pywikibot-core/build/1.0.76/job/tls8y6s73onoi0yf#L139

>  Could not find a version that satisfies the requirement multidict>=4.0 (from yarl; python_version in "3.4, 3.5, 3.6"->vcrpy->vcrpy-unittest->-r dev-requirements.txt (line 27)) (from versions: 1.0.0a0, 1.0.1, 1.0.2, 1.0.3, 1.1.0a0, 1.1.0a1, 1.1.0a2, 1.1.0a3, 1.1.0a5, 1.1.0a6, 1.1.0b1, 1.1.0b2, 1.1.0b3, 1.1.0b4, 1.1.0b5, 1.1.0b6, 1.1.0b7, 1.1.0b8, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0a0, 1.3.0a1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 3.0.0, 3.1.0, 3.1.1, 3.1.3a0, 3.1.3, 3.1.4a0, 3.1.4a1, 3.1.4a2, 3.1.4a3, 3.2.0a3, 3.2.0, 3.2.1a0, 3.3.0, 3.3.1)
> No matching distribution found for multidict>=4.0 (from yarl; python_version in "3.4, 3.5, 3.6"->vcrpy->vcrpy-unittest->-r dev-requirements.txt (line 27))

This is because [multidict v4.0.0 has dropped support for python_version<3.4.1](https://github.com/aio-libs/multidict/commit/85da277d2cb172b727c3d4204e445f04d8e01bdf). And [yarl v1.0.0 only supports multidict>=4.0](https://github.com/aio-libs/yarl/commit/f544a79f20572604ca6d9dc86ef21f7378a66f9d).

So, `vcrpy` should probably add `multidict<4.0.0,>=2.0` and `yarl<1.0.0` to its `Python==3.4.0` requirements.

**Comment by rosygupta** [comment]
Hey @5j9, can you please confirm is I'm facing the same issue via the trace below?
Thank you! :)

_`Installing vcrpy…
Collecting vcrpy
  Downloading vcrpy-1.11.1-py2.py3-none-any.whl
Collecting yarl; python_version in "3.4, 3.5, 3.6" (from vcrpy)
  Downloading yarl-1.1.1-cp35-cp35m-manylinux1_x86_64.whl (250kB)
Collecting PyYAML (from vcrpy)
  Downloading PyYAML-3.12.tar.gz (253kB)
Collecting wrapt (from vcrpy)
  Downloading wrapt-1.10.11.tar.gz
Requirement already satisfied: six>=1.5 in /home/rosy/.local/share/virtualenvs/oh-proj-management-hyE15nks/lib/python3.5/site-packages (from vcrpy)
Collecting multidict>=4.0 (from yarl; python_version in "3.4, 3.5, 3.6"->vcrpy)
  Downloading multidict-4.1.0-cp35-cp35m-manylinux1_x86_64.whl (471kB)
Requirement already satisfied: idna>=2.0 in /home/rosy/.local/share/virtualenvs/oh-proj-management-hyE15nks/lib/python3.5/site-packages (from yarl; python_version in "3.4, 3.5, 3.6"->vcrpy)
Building wheels for collected packages: PyYAML, wrapt
  Running setup.py bdist_wheel for PyYAML: started
  Running setup.py bdist_wheel for PyYAML: finished with status 'done'
  Stored in directory: /home/rosy/.cache/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
  Running setup.py bdist_wheel for wrapt: started
  Running setup.py bdist_wheel for wrapt: finished with status 'done'
  Stored in directory: /home/rosy/.cache/pip/wheels/56/e1/0f/f7ccf1ed8ceaabccc2a93ce0481f73e589814cbbc439291345
Successfully built PyYAML wrapt
Installing collected packages: multidict, yarl, PyYAML, wrapt, vcrpy
Successfully installed PyYAML-3.12 multidict-4.1.0 vcrpy-1.11.1 wrapt-1.10.11 yarl-1.1.1

Adding vcrpy to Pipfile's [dev-packages]…
Pipfile.lock (598668) out of date, updating to (01f209)…
Locking [dev-packages] dependencies…
pip9/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/vendor/pip9/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/vendor/pip9/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/vendor/pip9/_vendor/pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip9._vendor.pyparsing.ParseException: Expected stringEnd (at char 33), (line:1, col:34)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 66, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 54, in main
    results = resolve(packages, pre=do_pre, sources=project.sources, verbose=is_verbose, clear=do_clear)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 52, in resolve
    return pipenv.utils.resolve_deps(packages, which, project=project, pre=pre, sources=sources, clear=clear, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/utils.py", line 397, in resolve_deps
    resolved_tree, resolver = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/utils.py", line 327, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 331, in _iter_dependencies
    yield InstallRequirement.from_line(dependency_string, constraint=ireq.constraint)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/req/req_install.py", line 181, in from_line
    markers = Marker(markers)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_vendor/packaging/markers.py", line 282, in __init__
    raise InvalidMarker(err_str)
notpip._vendor.packaging.markers.InvalidMarker: Invalid marker: 'python_version in "3.4, 3.5, 3.6"; python_version in "3.4, 3.5, 3.6"', parse error at '; python'

/usr/local/lib/python2.7/dist-packages/pipenv/utils.py:1162: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-QGgfm3-requirements'>
  warnings.warn(warn_message, _ResourceWarning)`__

**Comment by 5j9** [comment]
@rosygupta, `InvalidMarker` error is usually caused by an old `setuptools` version. Try `pip install -U setuptools`.

**Comment by rosygupta** [comment]
Doesn't help. Says already upto date. 
"notpip._vendor.packaging.markers.InvalidMarker: Invalid marker: 'python_version in "3.4, 3.5, 3.6"; python_version in "3.4, 3.5, 3.6"', parse error at '; python'"--- You sure this is some error particular to my system itself?

**Comment by 5j9** [comment]
> You sure this is some error particular to my system itself?

Almost :) It seems that there have been a similar issue in [pipenv ](https://github.com/pypa/pipenv/pull/1624) which have resolved recently. Could try updating pipenv, too?

**Comment by rosygupta** [comment]
@5j9 tried that as well. I setup the whole thing on a new system with no old installs. facing the same issue. I basically tried installing vcrpy in this repo:  https://github.com/OpenHumans/oh-proj-management after setting up the repo as suggested in the `README.md`

**Comment by msheiny** [comment]
I'm also hitting exact same issue as @rosygupta  :| seems like a weird issue between `vcrpy` and `pipenv`  .

```
Locking [dev-packages] dependencies…
g.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip9._vendor.pyparsing.ParseException: Expected stringEnd (at char 33), (line:1, col:34)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/resolver.py", line 82, in <module>
    main()
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/resolver.py", line 71, in main
    clear=do_clear,
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/resolver.py", line 63, in resolve
    verbose=verbose,
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/utils.py", line 425, in resolve_deps
    pre,
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/utils.py", line 336, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, inresolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 200, in_resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 331, in_iter_dependencies
    yield InstallRequirement.from_line(dependency_string, constraint=ireq.constraint)
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/patched/notpip/req/req_install.py", line 181, in from_line
    markers = Marker(markers)
  File "/home/mike/.local/lib/python2.7/site-packages/pipenv/patched/notpip/_vendor/packaging/markers.py", line 282, in __init__
    raise InvalidMarker(err_str)
notpip._vendor.packaging.markers.InvalidMarker: Invalid marker: 'python_version in "3.4, 3.5, 3.6"; python_version in "3.4, 3.5, 3.6"', parse error at '; python'
```

**Comment by mukilkrishnan** [comment]
I am running into exactly the same issue as @rosygupta too. My guess is that this definitely has something to do with how `pipenv` deals with `vcrpy`:

```
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
parsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "C:\Python36\lib\site-packages\pipenv\vendor\pip9\_vendor\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Python36\lib\site-packages\pipenv\vendor\pip9\_vendor\pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "C:\Python36\lib\site-packages\pipenv\vendor\pip9\_vendor\pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Python36\lib\site-packages\pipenv\vendor\pip9\_vendor\pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip9._vendor.pyparsing.ParseException: Expected stringEnd (at char 33), (line:1, col:34)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\\Python36\\lib\\site-packages\\pipenv\\resolver.py", line 82, in <module>
    main()
  File "C:\\Python36\\lib\\site-packages\\pipenv\\resolver.py", line 71, in main
    clear=do_clear,
  File "C:\\Python36\\lib\\site-packages\\pipenv\\resolver.py", line 63, in resolve
    verbose=verbose,
  File "C:\Python36\lib\site-packages\pipenv\utils.py", line 425, in resolve_deps
    pre,
  File "C:\Python36\lib\site-packages\pipenv\utils.py", line 336, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "C:\Python36\lib\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "C:\Python36\lib\site-packages\pipenv\patched\piptools\resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "C:\Python36\lib\site-packages\pipenv\patched\piptools\resolver.py", line 331, in _iter_dependencies
    yield InstallRequirement.from_line(dependency_string, constraint=ireq.constraint)
  File "C:\Python36\lib\site-packages\pipenv\patched\notpip\req\req_install.py", line 181, in from_line
    markers = Marker(markers)
  File "C:\Python36\lib\site-packages\pipenv\patched\notpip\_vendor\packaging\markers.py", line 282, in __init__
    raise InvalidMarker(err_str)
notpip._vendor.packaging.markers.InvalidMarker: Invalid marker: 'python_version in "3.4, 3.5, 3.6"; python_version in "3.4, 3.5, 3.6"', parse error at '; python'
```
```
$ pipenv --version
pipenv, version 11.8.3

python --version
Python 3.6.4
```

Just to be sure, I uninstalled the Python 3.5.x that I had and installed 3.6.4 and updated `pip` and `pipenv`.

**Comment by aqw** [comment]
Related: #393

**Comment by jxltom** [comment]
For the issues related with pipenv locking, I think it is a pipenv issue, which is fixed in the recent PRs (probably released), instead of issue in this repo.
