### ISSUE TITLE
Can't use filter_post_data_parameters for requests with empty POST body

### ISSUE THREAD

**Issue by shtratos** [kevin1024/vcrpy#362]
### Reproducing issue

```python3
from pprint import pprint

import requests
import vcr

VCR = vcr.VCR(
    cassette_library_dir='/tmp/cassettes',
    filter_post_data_parameters=[('client_secret', 'dummy_secret')],
    record_mode="all"
)


def make_post(data):
    response = requests.post('https://httpbin.org/post', data=data, headers={'Accept': 'application/json'})
    pprint(response.json())


make_post(data='{}')
make_post(data=None)

with VCR.use_cassette('it_handles_empty_post_body') as cass:
    make_post(data='{}')
    make_post(data=None)

```

First 3 `make_post` invocations pass and print correct response, final one throws exception:

```
{'args': {},
 'data': '{}',
 'files': {},
 'form': {},
 'headers': {'Accept': 'application/json',
             'Accept-Encoding': 'gzip, deflate',
             'Connection': 'close',
             'Content-Length': '2',
             'Host': 'httpbin.org',
             'User-Agent': 'python-requests/2.18.4'},
 'json': {},
 'origin': '...',
 'url': 'https://httpbin.org/post'}
{'args': {},
 'data': '',
 'files': {},
 'form': {},
 'headers': {'Accept': 'application/json',
             'Accept-Encoding': 'gzip, deflate',
             'Connection': 'close',
             'Content-Length': '0',
             'Host': 'httpbin.org',
             'User-Agent': 'python-requests/2.18.4'},
 'json': None,
 'origin': '...',
 'url': 'https://httpbin.org/post'}
{'args': {},
 'data': '{}',
 'files': {},
 'form': {},
 'headers': {'Accept': 'application/json',
             'Accept-Encoding': 'gzip, deflate',
             'Connection': 'close',
             'Content-Length': '2',
             'Host': 'httpbin.org',
             'User-Agent': 'python-requests/2.18.4'},
 'json': {},
 'origin': '...',
 'url': 'https://httpbin.org/post'}
 
Traceback (most recent call last):
  File ".../vcr_bug.py", line 23, in <module>
    make_post(data=None)
  File ".../vcr_bug.py", line 14, in make_post
    response = requests.post('https://httpbin.org/post', data=data, headers={'Accept': 'application/json'})
  File ".../lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File ".../lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File ".../lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File ".../lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File ".../lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File ".../lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File ".../lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File ".../lib/python3.6/site-packages/vcr/stubs/__init__.py", line 215, in getresponse
    if self.cassette.can_play_response_for(self._vcr_request):
  File ".../lib/python3.6/site-packages/vcr/cassette.py", line 245, in can_play_response_for
    request = self._before_record_request(request)
  File ".../lib/python3.6/site-packages/vcr/config.py", line 253, in before_record_request
    request = function(request)
  File ".../lib/python3.6/site-packages/vcr/filters.py", line 100, in replace_post_data_parameters
    splits = [p.partition(b'=') for p in request.body.split(b'&')]
AttributeError: 'NoneType' object has no attribute 'split'
```

### Root cause

The cause seems to be lack of `None` check here:
https://github.com/kevin1024/vcrpy/blob/ab6e6b5b5d035f3a9dab5061f5cc610252c7c73c/vcr/filters.py#L100

### Fix

The fix would be to add a `None` check and skip filter in that case.

### Workaround

Currently I use this workaround that just sets body to empty string when it's `None`:

```python3

def _workaround_empty_post_body(request):
    """ Workaround a bug in VCR.py where it can't handle scrubbing secrets from POST requests without a body. """
    if request.method == 'POST' and not request.body:
        request.body = b''
    # manually perform filter_post_data_parameters=[('client_secret', 'dummy_secret')],
    return replace_post_data_parameters(request, {'client_secret': 'dummy_secret'})

VCR = vcr.VCR(before_record_request=_workaround_empty_post_body)
```

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
