### ISSUE TITLE
vcrpy throws an error if latest urllib3 is installed

### ISSUE THREAD

**Issue by scotloach** [kevin1024/vcrpy#688]
vcrpy won't import with latest urllib.

```
root@ef153dd6180d:/# python --version
Python 3.11.3
root@ef153dd6180d:/# pip install urllib3 vcrpy
Collecting urllib3
  Downloading urllib3-2.0.0-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.2/123.2 kB 10.0 MB/s eta 0:00:00
Collecting vcrpy
  Downloading vcrpy-4.2.1-py2.py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 45.4 MB/s eta 0:00:00
Collecting PyYAML
  Downloading PyYAML-6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 757.9/757.9 kB 51.1 MB/s eta 0:00:00
Collecting wrapt
  Downloading wrapt-1.15.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.9/78.9 kB 80.8 MB/s eta 0:00:00
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting yarl
  Downloading yarl-1.9.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 282.8/282.8 kB 161.6 MB/s eta 0:00:00
Collecting multidict>=4.0
  Downloading multidict-6.0.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.4/117.4 kB 136.7 MB/s eta 0:00:00
Collecting idna>=2.0
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 82.9 MB/s eta 0:00:00
Installing collected packages: wrapt, urllib3, six, PyYAML, multidict, idna, yarl, vcrpy
Successfully installed PyYAML-6.0 idna-3.4 multidict-6.0.4 six-1.16.0 urllib3-2.0.0 vcrpy-4.2.1 wrapt-1.15.0 yarl-1.9.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
root@ef153dd6180d:/# python
Python 3.11.3 (main, Apr 12 2023, 14:31:14) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vcr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/vcr/__init__.py", line 2, in <module>
    from .config import VCR
  File "/usr/local/lib/python3.11/site-packages/vcr/config.py", line 11, in <module>
    from .cassette import Cassette
  File "/usr/local/lib/python3.11/site-packages/vcr/cassette.py", line 12, in <module>
    from .patch import CassettePatcherBuilder
  File "/usr/local/lib/python3.11/site-packages/vcr/patch.py", line 41, in <module>
    _VerifiedHTTPSConnection = cpool.VerifiedHTTPSConnection
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'urllib3.connectionpool' has no attribute 'VerifiedHTTPSConnection'

```

**Comment by pquentin** [comment]
`VerifiedHTTPSConnection` is still here in urllib3 2.0. We stopped importing it from connectionpool.py but it still defined in connection.py. The vcrpy import was only working by accident here.

You can use `from urllib3.connection import VerifiedHTTPSConnection` instead but at this point I think it would be better to use the new name with `from urllib3.connection import HTTPSConnection`.

**Comment by saisankargochhayat** [comment]
Related: https://github.com/urllib3/urllib3/issues/3017

**Comment by alisakr** [comment]
I'm having the same issue, the issue appears to be that VERIFIEDHTTPSConnection is imported from connectionpool in vcr. But that is not where its declared but rather a place in urllib3 that used to import VERIFIEDHTTPSConnection as well.

**Comment by shifqu** [comment]
> `VerifiedHTTPSConnection` is still here in urllib3 2.0. We stopped importing it from connectionpool.py but it still defined in connection.py. The vcrpy import was only working by accident here: this was always documented to be in urllib3.connection.
> 
> You can use `from urllib3.connection import VerifiedHTTPSConnection` instead but at this point I think it would be better to use the new name with `from urllib3.connection import HTTPSConnection`.

@pquentin since the linked PR (#689) speaks about support for minimum supported versions, I think we best keep using VerifiedHTTPSConnection for now and just ensure that all `urllib3.connectionpool` imports are updated to point to `urllib3.connection` (At least for `HTTPConnection` and `HTTPSConnection`)

At least then we can close this issue and open a new one to discuss the minimum supported urllib version.

I'll try to submit a PR for my suggested fix.

**Comment by kuzminrobin** [comment]
> > `VerifiedHTTPSConnection` is still here in urllib3 2.0. We stopped importing it from connectionpool.py but it still defined in connection.py. The vcrpy import was only working by accident here: this was always documented to be in urllib3.connection.
> > You can use `from urllib3.connection import VerifiedHTTPSConnection` instead but at this point I think it would be better to use the new name with `from urllib3.connection import HTTPSConnection`.
> 
> @pquentin since the linked PR (#689) speaks about support for minimum supported versions, I think we best keep using VerifiedHTTPSConnection for now and just ensure that all `urllib3.connectionpool` imports are updated to point to `urllib3.connection` (At least for `HTTPConnection` and `HTTPSConnection`)
> 
> At least then we can close this issue and open a new one to discuss the minimum supported urllib version.
> 
> I'll try to submit a PR for my suggested fix.

One more vote for fixing this issue. Thank you for working on this!

Just in case I'll mention: **urllib3 v2.0 Migration Guide.** [AttributeError: module ‘urllib3.connectionpool’ has no attribute ‘VerifiedHTTPSConnection’](https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#attributeerror-module-urllib3-connectionpool-has-no-attribute-verifiedhttpsconnection). This item makes me think that you may want to
* switch from `connectionpool` to `connection` module,
* switch from `VerifiedHTTPSConnection` to `HTTPSConnection` class.

**Comment by hartwork** [comment]
> * switch from `connectionpool` to `connection` module,

That is #697.

> * switch from `VerifiedHTTPSConnection` to `HTTPSConnection` class.

That is potentially mistaken, please see https://github.com/kevin1024/vcrpy/pull/697#issuecomment-1550373205 .

**Comment by fiendish** [comment]
@kevin1024 can this issue stay open until the python<3.10 problem is worked out?

**Comment by hartwork** [comment]
@fiendish release >=4.3.1 has no issue because of 69db5c936f650cacb8107260e02ce935d2bf0220 urllib3 v2 cannot even be installed at the same time. So far my vote against a re-open. How would a re-open help you?

**Comment by hartwork** [comment]
@fiendish PS: We welcome help allowing support for Python <3.10 with urllib3 v2 installed if you have ideas how. Comment https://github.com/kevin1024/vcrpy/pull/699#issuecomment-1556165071 and after document how far we got in detail, economically.

**Comment by fiendish** [comment]
@hartwork It's a procedural request, not a technical one. people reference this issue when discussing the problem with their builds, and the problem isn't fixed for urllibv2 + py3.9. I've had requests already asking why particular urllib updates are blocked because the issue looks resolved until you go to the release notes.

> We welcome help allowing support for Python <3.10 with urllib3 v2 installed if you have ideas how

At the time I don't. I wish I did.

**Comment by hartwork** [comment]
Hi @fiendish I'm in a bit of a conflict here, maybe you can help me with that, let me explain. Issue "vcrpy throws an error if latest urllib3 is installed" is impossible to happen for both the latest release and Git `master` so in literal sense and development sense the ticket being closed as fixed is correct, with the current title.
What you're asking for is some open ticket "Please support urllib3 v2 with Python <3.10".  Since I am not aware of plans of anyone to do more work on that subject, I personally neither want to transform this closed ticket here into being that open ticket nor create a new dedicated ticket: I don't feel it's a good representation of reality. I would ask you: If you need an open ticket "Please support urllib3 v2 with Python <3.10", please create a new ticket with a sentence or two which other project needs this combination to work in reality. From I understand it could help your case and it would help my conflict. What do you think?

@jairhenrique @kevin1024 please be invited join in with your view on this, I have no intentions to misrepresent my view on this as the view of the whole team if it's not.

**Comment by kevin1024** [comment]
New ticket specifically about urllib3 v2 with Python <3.10 makes sense to me

**Comment by fiendish** [comment]
> Issue "vcrpy throws an error if latest urllib3 is installed" is impossible to happen

I think this depends on what one means by "latest" and "impossible". urllib3<2 is of course not the latest urllib3. And it of course is possible by upgrading urllib3 after vcrpy is installed.

But I recognize your dilemma and can just continue pointing at the reason given outside of this github issue.

**Comment by fiendish** [comment]
Also, thank you both for the fair consideration. I do appreciate the responses.

**Comment by hartwork** [comment]
> And it of course is possible by upgrading urllib3 after vcrpy is installed.

@fiendish I only considered combinations that would pass `pip3 check`, true.
