### ISSUE TITLE
AttributeError: 'VCRHTTPResponse' object has no attribute 'json'

### ISSUE THREAD

**Issue by gschnellOnera** [kevin1024/vcrpy#774]
I use pytest-recording, to mimic my http requests for testing. When switching to urllib3 to run the queries I encounter the following exception. `AttributeError: 'VCRHTTPResponse' object has no attribute 'json'`

```python
from urllib3 import PoolManager, make_headers

HTTP_PoolManager = PoolManager()
HTTP_HEADER_AUTH = make_headers(basic_auth='user:password')
req = HTTP_PoolManager.request('GET', url, headers=HTTP_HEADER_AUTH)
if (req.status != 200):
    if req.headers['content-type'].split(';')[0] == "application/json":
        return req.json()
#error managment
retrun None
```

Versions:
python 3.8.10
pytest-recording: 0.13.0
vcrpy: 5.1.0
urllib3: 2.0.4

Workaround:
```python
from urllib3 import PoolManager, make_headers
import json

HTTP_PoolManager = PoolManager()
HTTP_HEADER_AUTH = make_headers(basic_auth='user:password')
req = HTTP_PoolManager.request('GET', url, headers=HTTP_HEADER_AUTH)
if (req.status != 200):
    if req.headers['content-type'].split(';')[0] == "application/json":
        return json.loads(req.data)
#error managment
retrun None
```

**Comment by sergei-maertens** [comment]
Using requests library with urllib3 2.0.6 I'm getting similar JSON decode related errors, so I'm suspecting this has to do with urllib3 breaking changes

Traceback:

```
Traceback (most recent call last):
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bbt/code/open-forms/src/openforms/appointments/contrib/qmatic/tests/test_dates_list.py", line 32, in setUp
    locations = plugin.get_locations()
  File "/home/bbt/code/open-forms/src/openforms/appointments/contrib/qmatic/plugin.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/bbt/code/open-forms/src/openforms/appointments/contrib/qmatic/plugin.py", line 232, in get_locations
    for entry in response.json()["branchList"]
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Downgrading to urllib3 < 2.0 makes the problem go away.

**Comment by dmelo** [comment]
I might be wrong, but AFAIK, your issue will be solved after vcrpy releases a new version that supports urllib3 v2 -> https://github.com/kevin1024/vcrpy/issues/707

**Comment by hartwork** [comment]
@gschnellOnera the snippet you shared requires additional work to run in isolation. Could you turn it into a snippet reproducer that can be in isolation easily? Thanks in advance!

**Comment by kevin-paulson-mindbridge-ai** [comment]
Here is what I think would be helpful as it seems to be the same issue:
```py
import json
import pytest
import urllib3


class TestVCRJson:
    @pytest.mark.vcr
    def test_vcr_json(self):
        sent_dict = {"hi": "there"}
        req = urllib3.request("POST", "https://httpbin.org/post", json=sent_dict)
        resp_sent_dict = json.loads(req.json().get("data"))
        assert resp_sent_dict == sent_dict
```

```
AttributeError: 'VCRHTTPResponse' object has no attribute 'json'
```

Versions:

- python 3.13.1
- pytest-recording: 0.13.2
- vcrpy: 7.0.0
- urllib3: 2.3.0
