### ISSUE TITLE
Bug Report: Installation Failure of vcrpy>=5.0.0 in Conda Environment

### ISSUE THREAD

**Issue by cprogiopoulos** [kevin1024/vcrpy#828]
Dear vcrpy Developers,

I am writing to report an issue encountered during the installation of the vcrpy package (version >=5.0.0) within a Conda environment. Despite following standard procedures for environment setup and package installation, the installation process fails with the following error:

`pip install vcrpy>=5.0.0
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [23 lines of output]
    Traceback (most recent call last):
      File "C:\Users\user\miniconda3\envs\taskweaver\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
        main()
      File "C:\Users\user\miniconda3\envs\taskweaver\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user\miniconda3\envs\taskweaver\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
        return hook(config_settings)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user\AppData\Local\Temp\pip-build-env-uf5c_7t4\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
        return self._get_build_requires(config_settings, requirements=['wheel'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user\AppData\Local\Temp\pip-build-env-uf5c_7t4\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
        self.run_setup()
      File "C:\Users\user\AppData\Local\Temp\pip-build-env-uf5c_7t4\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
        super().run_setup(setup_script=setup_script)
      File "C:\Users\user\AppData\Local\Temp\pip-build-env-uf5c_7t4\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
        exec(code, locals())
      File "<string>", line 11, in <module>
      File "C:\Users\user\miniconda3\envs\taskweaver\Lib\encodings\cp1253.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9f in position 21: character maps to <undefined>
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

This error persists despite having created a new Conda environment with all packages fully upgraded and the PYTHONIOENCODING environment variable set to UTF-8.

Steps to Reproduce:

Create a new Conda environment: conda create -n my_env python=3.11
Activate the environment: conda activate my_env
Upgrade pip and setuptools: pip install --upgrade pip setuptools
Attempt to install vcrpy: pip install vcrpy>=5.0.0
Environment Details:

Operating System: Windows 10 x64
Conda Version: 24.1.2
Python Version: 3.11.8
PYTHONIOENCODING: UTF-8
This issue prevents the successful installation of the vcrpy package within Conda environments. Your attention to this matter and any assistance in resolving this issue would be greatly appreciated.

Please let me know if any additional information is required.

Thank you for your attention to this matter.

**Comment by 0t2** [comment]
I recently bumped into a similar issue.
I set  `PYTHONUTF8=1` in my Windows PowerShell with this command: `[System.Environment]::SetEnvironmentVariable('PYTHONUTF8', '1', 'User')`.
It works fine for me now.
